### ISSUE TITLE
[META] Make Documentation great (again)

### ISSUE THREAD

**Issue by Bendodroid** [HULKs/hulk#60]
# Introduction
- [x] Overview @PasGl @Bendodroid 

# Setup
- [x] Required Installation Steps @PasGl @Bendodroid 
- [x] Compiling for Webots @knoellle #4079 
- [x] Yocto setup @schmidma @h3ndrk 
- [x] Robot flashing @schmidma @h3ndrk
- [ ] Compiling for the NAO @knoellle 
- [ ] ...

# Framework
- [ ] All of it @schmidma @h3ndrk 

# Tooling
- [x] Overview @PasGl @Bendodroid 
- [x] Pepsi @knoellle #4081
- [ ] ~~Flora?~~
- [ ] Twix
- [ ] depp
- [ ] fanta
- [ ] machine-learning
- [ ] Behavior Simulator @PasGl 
  - [ ] sprite @PasGl 
- [ ] Debugging with GDB/LLDB
- [ ] ...

# Operating System
- [ ] All of it @schmidma @h3ndrk

# Robotics
- [ ] Perception
  - [x] Vision @knoellle #4089 
  - [ ] Audio
  - [ ] Filters
  - [ ] SPL Network @PasGl 
  - [ ] World State @PasGl
- [ ] Behavior @PasGl 
  - [ ] World state -> Actions -> MotionCommand @PasGl 
- [ ] Motion
  - [ ] Step planning
  - [ ] Walking
  - [ ] Kicking
  - [ ] Motion files @Aishkrish18
    - [ ] Stand-up etc.
- [ ] ...

# Workflow
- [ ] Development workflow
  - [ ] Coding Style @Bendodroid 
  - [ ] GitHub
    - [ ] CI
    - [ ] Board
  - [ ] Meetings
    - [ ] Test games
  - [ ] Test-driven development
    - [ ] Simulator
- [ ] Competition workflow
  - [ ] Meetings
  - [ ] Roles
- [ ] ...

**Comment by Bendodroid** [comment]
Uff puh, diese Wortwitze waren ja 2023 schon schwierig 😶‍🌫️

**Comment by oleflb** [comment]
This issue is hopelessly outdated. If we want to focus on documentation some time in the future, we need new planning anyway
